# Usage: 
#   pip install -e .

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyside6-template"
version = "1.0.0"
description = "A Qt6 application"
readme = "README.md"
authors = [
    {name = "Mag. Stefan Hagmann"},
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["pyside6", "gui", "desktop"]

dependencies = [
    "pyside6-essentials>=6.4.0",
    "turtle",
    "svg_turtle",
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
    "pyside6-tools>=6.4.0",  # For Qt Designer and pyside6-uic
    "build",
    "wheel",
    "pyinstaller>=6.0.0",
]





